apps/urls.py
from django.conf.urls.defaults import url, patterns, include
from django.conf import settings
from django.views.generic.simple import direct_to_template
from front.views import FrontView
from feeds import LatestFeed, LatestStoriesFeed, LatestStoriesSectionFeed, \
    LatestPostsAllBlogsFeed, LatestPostsSingleBlogFeed, LatestVideosFeed

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Google webmaster tools
    (r'^google9fc9f538545cc45e\.html$', direct_to_template, {'template': 'google9fc9f538545cc45e.html'}),

    # robots
    (r'^robots\.txt$', direct_to_template, {
        'template': 'robots.txt',
        'mimetype': 'text/plain',
        }),

    # front page
    url(r'^$', FrontView.as_view(), name='front'),

    # apps
    (r'^story/', include('stories.urls')),
    (r'^blogs/', include('blog.urls')),
    (r'^video/', include('video.urls')),
    (r'^staff/', include('staff.urls')),
    (r'^images/', include('images.urls')),
    (r'^masthead/', include('masthead.urls')),
    (r'^search/', include('search.urls')),
    (r'^archives/', include('archive.urls')),
    (r'^photos/', include('galleries.urls')),

    (r'^author/(?P<author>[\w-]+)/$', 'masthead.views.detail_author'),

    # admin
    (r'^admin/doc/', include('django.contrib.admindocs.urls')),
    (r'^admin/', include(admin.site.urls)),

    # tags
    url(r'^tags/$', 'tags.views.tags', name='tag-index'),
    (r'^tag/', include('tags.urls')),

    # bento
    (r'^boxes/', include('bento.urls')),

    # shorturls
    (r'^s/', include('shorturls.urls')),
)

urlpatterns += patterns('',
    (r'^rss/latest/$', LatestFeed()),
    (r'^rss/latest-stories/$', LatestFeed()),  # preserve old url
    (r'^rss/stories/$', LatestStoriesFeed()),
    (r'^rss/video/$', LatestVideosFeed()),
    (r'^rss/section/(?P<slug>.*)/', LatestStoriesSectionFeed()),
    (r'^rss/allblogs/$', LatestPostsAllBlogsFeed()),
    (r'^rss/blogs/(?P<slug>.*)/$', LatestPostsSingleBlogFeed()),
)

handler500 = 'stories.views.server_error'

if settings.DEBUG:
    urlpatterns += patterns('',
        (r'^media/(.*)$', 'django.views.static.serve', {
            'document_root': settings.MEDIA_ROOT,
            'show_indexes': True}),
    )

# pattern has to be last in the lookup order, because of the way we
# look up dynamic section urls
urlpatterns += patterns('',
    url(r'^(?P<section>[-\w]+)/$', 'stories.views.index_section',
        name='front-section'),
)

apps/sidebars/models.py
import datetime
from django.db import models
from django.db.models import Q
from structure.models import Issue, Author
from stories.models import Story, Photo
from imagekit.models import ImageModel

class PreviousStories:
    """
    Not actually a QuerySet Manager, but a class designed to provide manager-like
    functionality for the "previous stories" sidebar.
    """
    def __init__(self, section, num):
        self.section, self.num = section, num

    def get_future(self):
        latest = Issue.objects.published().latest()
        return Story.objects.select_related().filter(issue__pub_date__lt=latest.pub_date, \
            section=self.section).order_by('-structure_issue.pub_date')[:self.num]

    def get_by_issue(self, issue):
        return Story.objects.select_related().filter(issue__pub_date__lt=issue.pub_date, \
            section=self.section).order_by('-structure_issue.pub_date')[:self.num]


class CalendarSidebarManager(models.Manager):
    def get_by_issue(self, issue):
        """
        Takes an Issue object and returns all calendar items for the week
        following the publication date of the issue.
        """
        return self.get_query_set().filter(start_time__gte=issue.pub_date).filter(\
            start_time__lt=Issue.objects.next(issue).pub_date)

    def get_future(self):
        """
        Returns events in the future, calculated based on the current datetime.
        """
        return self.get_query_set().filter(Q(end_time__gte=datetime.datetime.now()) | \
            (Q(end_time__isnull=True) & Q(start_time__gte=datetime.datetime.now())))


class SportsSidebarManager(models.Manager):
    def get_by_issue(self, issue):
        """
        Takes an Issue object and returns all calendar items for the week
        following the publication date of the issue.
        """
        try:
            return self.get_query_set().filter(start_time__lte=issue.pub_date).filter(\
                start_time__gte=issue.get_previous_by_pub_date().pub_date)
        except:
            return self.get_query_set().filter(start_time__lte=issue.pub_date)

    def get_future(self):
        """
        Returns events in the future, calculated based on the current datetime.
        """
        try:
            latest = Issue.objects.published().latest()
        except:
            return None
        return self.get_query_set().filter(start_time__gte=latest.pub_date - \
            datetime.timedelta(7))


class StaticSidebarManager(models.Manager):
    def get_by_issue(self, issue):
        return self.get_query_set().filter(issue=issue)

    def get_future(self):
        try:
            latest = Issue.objects.published().latest()
        except:
            return None
        return self.get_query_set().filter(issue=latest)


class NewsCalendarItem(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()
    start_time = models.DateTimeField()
    end_time = models.DateTimeField(blank=True, null=True, default=None)
    location = models.CharField(max_length=255)
    event_type = models.ForeignKey('EventType', help_text='Not currently in use for \
        NewsCalendarItem.', blank=True, null=True)
    objects = CalendarSidebarManager()

    class Meta:
        ordering            = ('start_time','end_time')

    def __unicode__(self):
        return self.name


class ArtsCalendarItem(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True)
    start_time = models.DateField(help_text='Beginning of period for which \
        showtimes apply.')
    end_time = models.DateField(blank=True, null=True, default=None, help_text='End of \
        period for which showtimes apply. Optional.')
    location = models.CharField(max_length=255)
    event_type = models.ForeignKey('EventType')
    objects = CalendarSidebarManager()

    class Meta:
        ordering            = ('event_type','location','name','start_time')

    def __unicode__(self):
        return self.name


class ArtsCalendarShowtime(models.Model):
    time = models.TimeField()
    item = models.ForeignKey(ArtsCalendarItem)

    class Meta:
        verbose_name        = 'Event Showtime'
        ordering            = ('time',)


class TalkingHeadsItem(models.Model):
    question = models.CharField(max_length=255)
    location = models.CharField("at...", max_length=255, help_text="ex. \
        'the Common Ground', 'Jock Harty Arena', '368 Brock Street'")
    issue = models.ForeignKey(Issue, unique=True)
    objects = StaticSidebarManager()
    photos_by = models.ForeignKey(Author, null=True)

    def list_photographers(self):
        photogs = []
        name_in_list = False
        for answer in self.talkingheadsanswer_set.all():
            for photog in photogs:
                try:
                    if answer.photo.photographer.name == photog:
                        name_in_list = True
                        break
                except:
                    continue
            if name_in_list is False:
                try:
                    photogs.append(answer.photo.photographer.name)
                except:
                    continue
            name_in_list = False
        if len(photogs) > 2:
            for i in range(len(photogs)-2):
                photogs[i] = photogs[i] + ","
        if len(photogs) > 1:
            photogs[-1:-1] = ['and']
        return ' '.join(photogs)

    class Meta:
        ordering = ['issue']


class TalkingHeadsAnswer(ImageModel):
    name = models.CharField(max_length=255)
    quote = models.TextField()
    photo = models.ForeignKey(Photo, help_text="Photos should be 100 pixels square. \
        JPEGs only, please.", editable=False, null=True)
    image = models.ImageField(upload_to='talking_heads/%Y/%m/%d/', help_text="Photos \
        should be square. JPEGs only, please.")
    question = models.ForeignKey(TalkingHeadsItem)

    class IKOptions:
        # Defining ImageKit options
        spec_module = 'sidebars.heads_specs'
        cache_dir = 'photo_cache'
        image_field = 'image'

    class Meta:
        order_with_respect_to   = 'question'


class EventType(models.Model):
    event_type = models.CharField(max_length=255)

    def __unicode__(self):
        return self.event_type


##class Announcement(models.Model):
##    head = models.CharField(max_length=255)
##    blurb = models.TextField()
##    start_date = models.DateField()
##    end_date = models.DateField()


class SportsCalendarItem(models.Model):
    sport = models.ForeignKey('SportType')
    start_time = models.DateTimeField()
    location = models.CharField(max_length=255)
    ticket_info = models.TextField(blank=True)
    objects = SportsSidebarManager()

    def is_played(self):
        return self.start_time < datetime.datetime.now()

    class Admin:
        fields = (
            ('Pre-event info', {
                'fields': ('sport', 'start_time', 'location', 'ticket_info'),
                'description': 'For team events, fill in the pre-event info and the two \
                    teams under "Team Result." For individual events, fill in the \
                    pre-event info and leave "Individual Results" blank. After the \
                    game/event is over, fill in the results as needed. If you require \
                    more fields for individual results, click "Save and continue editing" \
                    after filling out all available result fields.'
            }),
        )
        list_display        = ('sport', 'location', 'start_time', 'is_played')
        list_filter         = ('start_time', 'sport')
        ordering            = ('-start_time',)

    class Meta:
        ordering            = ('start_time', 'sport')

    def __unicode__(self):
        if self.sportsteamgamescore_set.count() == 0:
            return "%s @ %s, %s" % (self.sport.name, self.location, self.start_time)
        else:
            teams = self.sportsteamgamescore_set.all()[0]
            return "%s, %s vs. %s, %s" % (self.sport.name, teams.home_team, \
                teams.away_team, self.start_time)


class SportsTeamGameScore(models.Model):
    home_team = models.CharField(max_length=255)
    home_score = models.PositiveSmallIntegerField(blank=True, null=True)
    away_team = models.CharField(max_length=255)
    away_score = models.PositiveSmallIntegerField(blank=True, null=True)
    event = models.ForeignKey(SportsCalendarItem) #, edit_inline=models.TABULAR,
        #min_num_in_admin=1, max_num_in_admin=1, num_in_admin=1, num_extra_on_change=0

    class Meta:
        verbose_name = 'Team Result'


class SportsIndividualScore(models.Model):
    event_detail = models.CharField('Individual event name', max_length=255, blank=True)
    name = models.CharField(max_length=255)
    place = models.PositiveSmallIntegerField(blank=True, null=True)
    result_detail = models.CharField(max_length=255, blank=True)
    home_team = models.BooleanField("Queen's athlete?")
    school = models.CharField("School name (if not Queen's)", max_length=255, blank=True)
    event = models.ForeignKey(SportsCalendarItem) #, edit_inline=models.TABULAR,
        # min_num_in_admin=1, num_in_admin=9, num_extra_on_change=2

    class Meta:
        verbose_name        = 'Individual Result'
        ordering            = ('event_detail', 'place')


class SportType(models.Model):
    name = models.CharField(max_length=255)

    class Admin:
        pass

    def __unicode__(self):
        return self.name

apps/templates/sidebars/arts_sidebar.html
{% load typogrify %}
{% if is_empty %}
{% else %}
	<div id="content-sidebar">
	<h3>Get Out There</h3>
	{% regroup items|dictsort:"event_type.event_type" by event_type as types %}
	{% for type in types %}
		<p class="sidebar-calendar-date">{{ type.grouper }}</p>
		{% regroup type.list|dictsort:"location" by location as venues %}
		{% for venue in venues %}
			<div class="sidebar-artscalendar-item">
			<h5 class="sidebar-calendar-name">{{ venue.grouper }}</h5>
			{% regroup venue.list|dictsort:"name" by name as events %}
			{% for event in events %}
				<p class="sidebar-artscalendar-eventname">{{ event.grouper }}</p>
				{% for item in event.list|dictsort:"start_time" %}
					{% ifchanged item.description %}<p class="sidebar-calendar-details">{{ item.description|widont }}</p>{% endifchanged %}
					<p class="sidebar-artscalendar-time">{{ item.start_time|date:"F j" }}{% if item.end_time %} &ndash; {{ item.end_time|date:"F j" }}{% endif %}{% if item.artscalendarshowtime_set.all %}: {% endif %}
					{% for showtime in item.artscalendarshowtime_set.all %}
						{{ showtime.time|time:"P"|widont }}{% if not forloop.last %},{% endif %}
					{% endfor %}</p>
				{% endfor %}
			{% endfor %}
			</div>
		{% endfor %}
	{% endfor %}
	</div>
{% endif %}

apps/templates/sidebars/eds_sidebar.html
{% if is_empty %}
{% else %}
	<div id="content-sidebar">
		<h3>Talking Heads</h3>
	{% for item in items %}
		<p class="sidebar-heads-location">...at {{ item.location }}</p>
		<h4 class="sidebar-heads-question">{{ item.question }}</h4>
		{% for answer in item.talkingheadsanswer_set.all %}
			<img src="{{ answer.photo.get_photo_url }}" class="sidebar-heads-image"/>
			<h5 class="sidebar-heads-person">{{ answer.name }}</h5>
			<p class="sidebar-heads-quote">{{ answer.quote }}</p>
		{% endfor %}
	{% endfor %}
	</div>
{% endif %}

apps/templates/sidebars/heads_sidebar.html
{% load typogrify %}

{% if is_empty %}
{% else %}
	<div id="content-sidebar">
	<h3>Talking Heads</h3>
	{% for item in items %}
		<p class="sidebar-heads-location">...{{ item.location|typogrify }}</p>
		<h4 class="sidebar-heads-question">{{ item.question|typogrify }}</h4>
		{% for answer in item.talkingheadsanswer_set.all %}
		<div class="sidebar-heads-answer clearfix">
			{% if answer.photo %}
			<img src="{{ answer.photo.thumbnail_image.url }}" class="sidebar-heads-image"/>
			{% else %}
			<img src="{{ answer.thumbnail_image.url }}" class="sidebar-heads-image"/>
			{% endif %}
			<p class="sidebar-heads-quote">{{ answer.quote|typogrify }}</p>
			<p class="sidebar-heads-person">{{ answer.name|typogrify }}</p>
		</div>
		{% endfor %}
		{% if item.photos_by %}
		<p class="sidebar-heads-credits">Photos by {{ item.photos_by.name|typogrify }}</p>
		{% else %}
		<p class="sidebar-heads-credits">Photos by {{ item.list_photographers|typogrify }}</p>
		{% endif %}
	{% endfor %}
	</div>
{% endif %}

apps/templates/sidebars/news_sidebar.html
{% load typogrify %}
{% if is_empty %}
{% else %}
	<div id="content-sidebar">
	<h3>Campus Calendar</h3>
	{% for item in items %}
		{% ifchanged item.start_time.date %}<p class="sidebar-calendar-date">{{ item.start_time.date|date:"F j" }}</p>{% endifchanged %}
		<h5 class="sidebar-calendar-name">{{ item.name }}</h5>
		<p class="sidebar-calendar-details">{{ item.description|widont }}</p>
		<p class="sidebar-calendar-location">{{ item.location }}</p>
		<p class="sidebar-calendar-time">{{ item.start_time|date:"P" }}{% if item.end_time %}-{{ item.end_time|date:"P" }}{% endif %}</p>
	{% endfor %}
	</div>
{% endif %}

apps/templates/sidebars/previously_sidebar.html
{% load typogrify %}
{% if is_empty %}
{% else %}
	<div id="content-sidebar">
	<h3>Previously</h3>
	{% for item in items %}
		<p class="sidebar-previous-date">{{ item.issue.pub_date|date:"F j, Y" }}</p>
		<h4 class="sidebar-previous-head"><a href="{{ item.get_absolute_url }}">{{ item.head }}</a></h4>
		<p class="sidebar-previous-summary">{{ item.summary|widont }}</p>
	{% endfor %}
	</div>
{% endif %}

apps/templates/sidebars/sports_sidebar.html
{% load typogrify %}
{% if is_empty %}
{% else %}
	<div id="content-sidebar">
	{% regroup items|dictsortreversed:"is_played" by is_played as times %}
	{% for time in times %}
		{% if time.grouper %}
			<h3>Scoreboard</h3>
			{% regroup time.list|dictsort:"sport.name" by sport as sports %}
			{% for sport in sports %}
				<p class="sidebar-calendar-date">{{ sport.grouper }}</p>
				{% for item in sport.list %}
					{% ifchanged item.start_time.date %}
						<p class="sidebar-sports-date">{{ item.start_time|date:"F j" }}</p>
					{% endifchanged %}
					<div class="sidebar-sports-item">
					{% if item.sportsteamgamescore_set.all %}
						{% for score in item.sportsteamgamescore_set.all %}
							{% ifequal score.home_score None %}
								<p class="sidebar-sports-teams">{{ score.home_team }} vs. {{ score.away_team }}: results pending</p>
							{% else %}
								<p class="sidebar-sports-teams">{{ score.home_team }} {{ score.home_score }}, {{ score.away_team }} {{ score.away_score }}</p>
							{% endifequal %}
						{% endfor %}
					{% else %}
						{% if item.sportsindividualscore_set.all %}
							{% regroup item.sportsindividualscore_set.all by event_detail as ind_events %}
							{% for ind_event in ind_events %}
								<div class="sidebar-sports-item">
								<p class="sidebar-sports-eventdetail">{{ ind_event.grouper }}</p>
								{% for result in ind_event.list %}
									<p class="sidebar-sports-indresult{%if result.home_team %}-queens{% endif %}">{{ result.place }}. {{ result.name }}, {% if result.home_team %}Queen's{% else %}{{ result.school }}{% endif %} {% if result.result_detail %}({{ result.result_detail }}){% endif %}</p>
								{% endfor %}
								</div>
							{% endfor %}
						{% else %}
							<p class="sidebar-sports-teams">Results pending</p>
						{% endif %}
					{% endif %}
					</div>
				{% endfor %}
			{% endfor %}
		{% else %}
			<h3>Upcoming Games</h3>
			{% regroup time.list|dictsort:"sport.name" by sport as sports %}
			{% for sport in sports %}
				<p class="sidebar-calendar-date">{{ sport.grouper }}</p>
				{% for item in sport.list %}
					{% ifchanged item.start_time.date %}
						<p class="sidebar-sports-date">{{ item.start_time|date:"F j" }}</p>
					{% endifchanged %}
					<div class="sidebar-sports-item">
					{% if item.sportsteamgamescore_set.all %}
						{% for score in item.sportsteamgamescore_set.all %}
							<p class="sidebar-sports-teams">{{ score.home_team }} vs. {{ score.away_team }}</p>
						{% endfor %}
					{% endif %}
					{% if item.ticket_info %}<p class="sidebar-sports-description">{{ item.ticket_info }}</p>{% endif %}
					<p class="sidebar-sports-location">{{ item.location }}</p>
					<p class="sidebar-sports-time">{{ item.start_time|date:"P" }}</p>
					</div>
				{% endfor %}
			{% endfor %}
		{% endif %}
	{% endfor %}
	</div>
{% endif %}