apps/blog/urls.py
from django.conf.urls.defaults import patterns, url
from blog.views import all_blogs, blog_detail, blog_archive_month, blog_index

urlpatterns = patterns('',
    url(r'^archived/$', all_blogs, {'active': False}, name='all_blogs_archived'),
    url(r'^(?P<blog>[-\w]+)/(?P<year>\d{4})/(?P<month>\d{2})/(?P<slug>[-\w]+)/$',
        blog_detail),
    url(r'^(?P<blog>[-\w]+)/(?P<year>\d{4})/(?P<month>\d{2})/page/(?P<page>\d{1,5})/$',
        blog_archive_month, name='blog_archive_month_pages'),
    url(r'^(?P<blog>[-\w]+)/(?P<year>\d{4})/(?P<month>\d{2})/$', blog_archive_month,
        name='blog_archive_month_front'),
    url(r'^(?P<blog>[-\w]+)/page/(?P<page>\d{1,5})/$', blog_index,
        name='blog-index'),
    url(r'^(?P<blog>[-\w]+)/$', blog_index, name='blog-index'),
    url(r'^$', all_blogs, name='all_blogs'),
)

apps/urls.py
from django.conf.urls.defaults import url, patterns, include
from django.conf import settings
from django.views.generic.simple import direct_to_template
from front.views import FrontView
from feeds import LatestFeed, LatestStoriesFeed, LatestStoriesSectionFeed, \
    LatestPostsAllBlogsFeed, LatestPostsSingleBlogFeed, LatestVideosFeed

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Google webmaster tools
    (r'^google9fc9f538545cc45e\.html$', direct_to_template, {'template': 'google9fc9f538545cc45e.html'}),

    # robots
    (r'^robots\.txt$', direct_to_template, {
        'template': 'robots.txt',
        'mimetype': 'text/plain',
        }),

    # front page
    url(r'^$', FrontView.as_view(), name='front'),

    # apps
    (r'^story/', include('stories.urls')),
    (r'^blogs/', include('blog.urls')),
    (r'^video/', include('video.urls')),
    (r'^staff/', include('staff.urls')),
    (r'^images/', include('images.urls')),
    (r'^masthead/', include('masthead.urls')),
    (r'^search/', include('search.urls')),
    (r'^archives/', include('archive.urls')),
    (r'^photos/', include('galleries.urls')),

    (r'^author/(?P<author>[\w-]+)/$', 'masthead.views.detail_author'),

    # admin
    (r'^admin/doc/', include('django.contrib.admindocs.urls')),
    (r'^admin/', include(admin.site.urls)),

    # tags
    url(r'^tags/$', 'tags.views.tags', name='tag-index'),
    (r'^tag/', include('tags.urls')),

    # bento
    (r'^boxes/', include('bento.urls')),

    # shorturls
    (r'^s/', include('shorturls.urls')),
)

urlpatterns += patterns('',
    (r'^rss/latest/$', LatestFeed()),
    (r'^rss/latest-stories/$', LatestFeed()),  # preserve old url
    (r'^rss/stories/$', LatestStoriesFeed()),
    (r'^rss/video/$', LatestVideosFeed()),
    (r'^rss/section/(?P<slug>.*)/', LatestStoriesSectionFeed()),
    (r'^rss/allblogs/$', LatestPostsAllBlogsFeed()),
    (r'^rss/blogs/(?P<slug>.*)/$', LatestPostsSingleBlogFeed()),
)

handler500 = 'stories.views.server_error'

if settings.DEBUG:
    urlpatterns += patterns('',
        (r'^media/(.*)$', 'django.views.static.serve', {
            'document_root': settings.MEDIA_ROOT,
            'show_indexes': True}),
    )

# pattern has to be last in the lookup order, because of the way we
# look up dynamic section urls
urlpatterns += patterns('',
    url(r'^(?P<section>[-\w]+)/$', 'stories.views.index_section',
        name='front-section'),
)

apps/blog/models.py
import re
from datetime import datetime
from django.db import models
from django.db.models import permalink
from django.template.defaultfilters import slugify

from imagekit.models import ImageModel
from tagging.fields import TagField

from structure.models import Author
from images.models import Image


class BlogImage(ImageModel):
    slug = models.SlugField()
    image = models.ImageField(upload_to="blogs/",
        help_text="Bigger is better. Jpeg.")

    class IKOptions:
        # Defining ImageKit options
        spec_module = 'blog.blog_specs'
        cache_dir = 'photo_cache'
        image_field = 'image'

    class Meta:
        verbose_name = 'Blog Header Image'
        verbose_name_plural = 'Blog Header Images'

    def __unicode__(self):
        return self.slug


class Blog(models.Model):
    title = models.CharField(max_length=255, unique=True,
        help_text='Short name for the blog.')
    slug = models.SlugField(unique=True)
    teaser = models.CharField(max_length=100, help_text='Short, one-line \
        teaser for the blog. Seen on the global blog pull-down menu.')
    description = models.TextField(blank=True,
        help_text="Description of the blog's content.")
    bloggers = models.ManyToManyField(Author)
    active = models.BooleanField('Blog is active?', default=True,
        help_text='You can disable blogs that are no longer being updated. \
            They will be filed under the Archived Blogs page.')
    image = models.ForeignKey(BlogImage, blank=True, null=True)
    order = models.IntegerField(help_text="Order that the Blog will show up on \
        the Blog page.")

    class Meta:
        ordering = ('title',)

    @models.permalink
    def get_absolute_url(self):
        return('blog-index', (), {
            'blog': self.slug})

    def __unicode__(self):
        return self.title


class EntryManager(models.Manager):
    ## single-blog/all blogs queryset functions
    def published(self):
        return self.get_query_set().filter(is_published=True).filter(
            pub_date__lte=datetime.now())

    def get_month(self, year, month):
        return self.published().filter(pub_date__year=year, pub_date__month=month)

    def get_by_author(self, author_id):
        return self.published().filter(author=author_id)

    ## multiple-blog queryset functions
    def published_on_blog(self, blog):
        return self.published().filter(blog__slug__exact=blog)

    def get_month_on_blog(self, blog, year, month):
        return self.get_month(year, month).filter(blog__slug__exact=blog)

    def get_author_on_blog(self, blog, author_id):
        return self.get_by_author(author_id).filter(blog__slug__exact=blog)

    '''
    Sets up the ability to add custom methods to QuerySets

    def get_query_set(self):
        return self.model.QuerySet(self.model)
    def __getattr__(self, name, *args):
        if name.startswith('_'):
            raise AttributeError
        return getattr(self.get_query_set(), name, *args)
    '''

    def has_photos(self, blog):
        entries = self.published().filter(blog=blog).order_by('-pub_date')
        s_re = re.compile('<!--image:"([-\w]+)"-->', re.IGNORECASE)
        results = []
        for entry in entries:
            try:
                Image.objects.get(slug__exact=s_re.findall(entry.content)[0])
                results.append(entry)
            except IndexError:
                continue
        return results


class Entry(models.Model):
    title = models.CharField(max_length=255,
        help_text='Title of the blog post.')
    blog = models.ForeignKey(Blog)
    slug = models.SlugField()
    author = models.ForeignKey(Author)
    tags = TagField(
        help_text='Post Tags and Label. Use this to apply tags to the post. \
            Use commas to separate tags. The first tag will be the post\'s \
            label. For example: \"Student Ghetto, EngSoc, Town-Gown, \
            Aberdeen\"')
    content = models.TextField()
    is_published = models.BooleanField('Published', default=True,
        help_text='When you want to publish a blog post, make sure this box \
        is checked; if you just want to save a draft, leave this unchecked.')
    enable_comments = models.BooleanField(default=True,
        help_text='Toggle to turn comments on or off for this post.')
    date_saved = models.DateTimeField(editable=False, default=datetime.now)
    date_draft_or_publish = models.DateTimeField(editable=False,
        default=datetime.now)
    pub_date = models.DateTimeField(default=datetime.now,
        help_text='If you wish to keep a post hidden until some time in the \
            future, check the Published box and change this date to when you \
            want the post to go live.')
    is_tweeted = models.BooleanField(editable=False, default=False)
    objects = EntryManager()

    class Meta:
        ordering = ('-date_draft_or_publish', '-pub_date', '-date_saved',
            'title')
        verbose_name_plural = 'entries'
        permissions = (
            ('change_own_entry', 'Can change own entry'),
            ('view_draft_entry', 'Can view all drafts and future posts'),
            ('view_own_draft', 'Can view own drafts and future posts'),
            ('delete_own_draft', 'Can delete own draft'),
            ('moderate_entry', 'Can moderate comments on entries')
        )
        get_latest_by = '-pub_date'

    def save(self, *args, **kwargs):
        # set pub_date time
        if self.is_published is True and self.pub_date is None:
            self.pub_date = datetime.now()
        elif self.is_published is False and self.pub_date is not None:
            self.pub_date = None
        # set date_draft_or_publish time
        if self.pub_date is None and self.date_draft_or_publish is None:
            self.date_draft_or_publish = datetime.now()
        elif self.pub_date is not None:
            self.date_draft_or_publish = self.pub_date
        # set slug
        if self.slug == 'slug-not-set' or self.slug is None:
            self.slug = slugify(self.title)[0:49]
        self.date_saved = datetime.now()
        super(Entry, self).save(*args, **kwargs)

    def first_photo(self):
        s_re = re.compile('<!--image:"([-\w]+)"-->', re.IGNORECASE)
        try:
            photo = Image.objects.get(slug__exact=s_re.findall(self.content)[0])
            return photo
        except IndexError:
            return False

    def model_type(self):
        return self.__class__.__name__

    def __unicode__(self):
        return '%s' % (self.title)

    def get_absolute_url(self):
        return('blog.views.blog_detail', (), {
            'blog': self.blog.slug,
            'year': self.pub_date.strftime('%Y'),
            'month': self.pub_date.strftime('%m'),
            'slug': self.slug})
    get_absolute_url = permalink(get_absolute_url)

    def get_twitter_message(self):
        return u'%s: %s' % (self.title, self.content)

apps/blog/views.py
from datetime import datetime
from django.views.generic.list_detail import object_detail, object_list
from django.shortcuts import get_object_or_404, render
from django.http import Http404, HttpResponseRedirect
from blog.models import Blog, Entry
from structure.models import Author
from tagging.models import Tag
from tagging.utils import calculate_cloud


def all_blogs(request, active=True):
    """
    List of all blogs. Defaults to listing active blogs.
    """
    blogs = Blog.objects.filter(active=active).order_by('order')
    featured = []
    for blog in blogs:
        featured.extend(Entry.objects.has_photos(blog)[:1])
    latest = Entry.objects.filter(pub_date__lte=datetime.now()).order_by('-pub_date')[:5]
    c = {
        'blogs': blogs,
        'active': active,
        #'archives': Blog.objects.filter(active=False).count() > 0,
        'featured': featured,
        'latest': latest,
    }
    return render(request, 'blog/blog_list.html', c)


def blog_index(request, blog, page=1):
    """
    Blog front page. Displays latest blog posts, excluding future posts.
    Paginated.
    """
    blog_tags = Tag.objects.usage_for_model(Entry, counts=True,
        filters=dict(blog__slug=blog))
    cloud = calculate_cloud(blog_tags)
    blog_obj = get_object_or_404(Blog, slug=blog)
    qs = Entry.objects.published_on_blog(blog).order_by('-pub_date')
    c = {'blog': blog_obj,
        'blog_tags': cloud}
    return object_list(request, queryset=qs, paginate_by=10, allow_empty=False,
        page=page, extra_context=c)


def blog_archive_month(request, blog, year, month, page=1):
    """
    Monthly archives. Displays all blog posts in a given month. Paginated.
    """
    year = int(year)
    month = int(month)
    qs = Entry.objects.get_month_on_blog(blog, year, month)
    if qs.count() > 0:
        c = {
            'blog': get_object_or_404(Blog, slug=blog),
            'month': datetime(year, month, 1)
        }
        if month == 1:
            c['prev_month'] = datetime(year - 1, 12, 1)
        else:
            c['prev_month'] = datetime(year, month - 1, 1)
        if month == 12:
            c['next_month'] = datetime(year + 1, 1, 1)
        else:
            c['next_month'] = datetime(year, month + 1, 1)
        return object_list(request, queryset=qs, paginate_by=10, allow_empty=False,
            extra_context=c, page=page)
    else:
        raise Http404


def blog_detail(request, blog, year, month, slug):
    """
    Entry detail. Displays a single full post, identified by its slug.
    """
    blog_obj = get_object_or_404(Blog, slug=blog)
    entry = get_object_or_404(Entry, slug=slug, blog=blog_obj)
    return render(request, 'blog/entry_detail.html', {
        'blog': blog_obj,
        'entry': entry,
        })


def blog_draft_detail(request, post_id):
    """
    Draft entry detail. Displays a draft entry if the user is logged in and has
    the correct permissions.
    """
    if not request.user.is_authenticated():
        # pretend nothing's here, raise a 404
        raise Http404
    else:
        # test for object's existence
        entry = get_object_or_404(Entry, pk=post_id)
        if request.user.has_perm('blog.view_draft_entry') or (
            request.user.has_perm('blog.view_own_draft') and request.user ==
                entry.author.user):
            qs = Entry.objects.all()
            c = {'draft': True}
            if not entry.is_published:
                return object_detail(request, queryset=qs, object_id=post_id, extra_context=c)
            else:
                return HttpResponseRedirect(entry.get_absolute_url())
        else:
            raise Http404


def blog_all_authors(request, blog):
    """
    All author profiles for an individual blog on one page. Whee!
    """
    qs = Author.objects.select_related(depth=2).filter(entry__blog__slug__exact=blog)
    c = {'blog': get_object_or_404(Blog, slug=blog)}
    return object_list(request, queryset=qs, extra_context=c)

apps/templates/blog/base.html
{% extends 'base.html' %}
{% load markup %}
{% load archives %}

{% block title %}{{ blog.title }} - {{ block.super }}{% endblock title %}

    <!-- google_ad_section_start -->
    {% block content %}
            {% block breadcrumb %}{% endblock %}

            {% block header %}{% endblock %}

            <div class="block">

                <div class="blog-content column span-16 colborder">
                    {% block blog-content %}{% endblock blog-content %}
                </div>

                <div class="blog-sidebar column span-7 last">
                    {% block blog-actions %}<p><a href="/rss/blogs/{{ blog.slug }}/"><img src="{{ STATIC_URL }}img/feed.png">&ensp;Latest posts (RSS 2.0)</a></p>{% endblock blog-actions %}
                    <p class="blog-label">About {{ blog.title }}</p>
                    <p>{{ blog.description|markdown }}</p>
                    <p class="blog-label">Archives by date</p>
                    <ul>
                    {% blog_dates blog.slug as dates %}
                    {% for date in dates %}
                        <li><a href="{% url blog_archive_month_front blog.slug,date.year,date|date:"m" %}" title="{{ date|date:"F Y" }}">{{ date|date:"F Y" }}</a></li>
                    {% endfor %}
                    </ul>
                    <p class="blog-label">Archives by Tag</p>
                    <ul>
                    {% for tag in blog_tags %}
                        <li class="blogtag-{{tag.font_size}}"><a href="/tag/{{tag.name|urlencode}}/">{{ tag }}</a></li>
                    {% endfor %}
                    </ul>

                    {% block blog-filter %}{% endblock blog-filter %}
                </div>

            </div><!-- block-->
    {% endblock content %}
<!-- google_ad_section_end -->

apps/templates/blog/blog_list.html
{% extends 'stories/index_section.html' %}
{% load typogrify %}
{% load custom_html %}
{% load navigation %}
{% load sidebartags %}

{% block headcode %}
{% if active %}<link rel="alternate" type="application/rss+xml" title="Latest posts from all blogs (RSS 2.0)" href="/rss/blogs/all/" />{% endif %}
{{ block.super }}
{% endblock headcode %}

{% block title %}Blogs{{ block.super }}{% endblock title %}

    {% block actions %}
        {% if active %}<li><a href="/rss/allblogs/"><span><img src="{{ STATIC_URL }}img/feed.png" />Latest blogs RSS</span></a></li>{% endif %}
    {% endblock actions %}

    {% block content %}
        {% block breadcrumb %}<div id="breadcrumb"><a href="/">Home</a><span class="divider"></span><span class="current">Blogs</span></div>{% endblock %}
        <div class="section-header">
            <h1>Blogs</h1>
        </div>

        <div class="hr dblmargin"><hr></div>

        <div class="block">

            <div class="featured column span-16 colborder"><!--featured box-->

                    <div id="slider-wrapper">

                        <div id="slider" class="nivoSlider" style="margin-right: 0px;">
                        {% for entry in featured %}
                            <img src="{{ entry.story_thumb.display.url }}" alt="{{ entry.title }}" class="slideshow-featured-img" title="#caption{{ entry.id }}"/>
                        {% endfor %}
                        </div>
                        {% for entry in featured %}
                        <div id="caption{{ entry.id }}" class="nivo-html-caption">
                            <p class="slider-story label"><a href="{{ entry.blog.get_absolute_url }}">{{ entry.blog }}</a></p>
                            <h2><a href="{{ entry.get_absolute_url }}">{{ entry.title|striptags|choptext:"42"|stripspace|convert_entities|safe }}</a></h2>
                            {{ entry.content|stripspace|convert_entities|truncatewords:38|striptags|safe }}
                        </div>
                        {% endfor %}

                    </div>

            </div><!--featured box-->

            <div id="stories-other" class="latest column span-7 last">
                <h3>Latest Posts <span class="feed"><a href="/rss/allblogs/"><img src="{{ STATIC_URL }}img/feed-small.png" />RSS Feed</a></span></h3>
                <hr>
                <ul>
                {% for entry in latest %}
                    <li><p class="label"><a href="{{ entry.blog.get_absolute_url }}">{{ entry.blog }}</a></p>
                        <h5><a href="{{ entry.get_absolute_url }}">{{ entry.title }}</a></h5>
                        <p class="pub_date">{{ entry.pub_date|time_since }}</p>
                    </li>
                {% endfor %}
                </ul>
            </div>

        </div><!--block-->

        <div class="hr dblmargin"><hr></div>

        <div class="block">

            <div id="other-stories" class="column span-24 last">

                {% for blog in blogs %}
                <div class="latest-section">
                    <a href="{{ blog.get_absolute_url }}">{% if blog.image %}<img src="{{ blog.image.front_image.url }}" /></a>{% endif %}
                    <h2 class="latest-section-head"><a href="{{ blog.get_absolute_url }}">{{ blog.title }}</a></h2>
                    <p class="latest-section-summary">{{ blog.description|typogrify|safe }}</p>

                    <p><a href="/rss/blogs/{{ blog.slug }}"><img src="{{ STATIC_URL }}img/feed-icon-10x10.gif">&ensp;Latest posts feed</a></p>
                    <div class="blog-recent-posts latest">
                        <ul>
                        {% for post in blog.entry_set.published|slice:":2" %}
                            <li><p class="label">Posted {{ post.pub_date|time_since }}</p>
                            <h5><a href="{{ post.get_absolute_url }}">{{ post.title|typogrify }}</a></h5></li>
                        {% endfor %}
                        </ul>
                    </div>
                </div>
                {% endfor %}

            </div>

        </div>

    {% endblock content %}

{% block footercode %}
    $(window).load(function() {
       $('#slider').nivoSlider({
            directionNav:true,
            controlNav:false,
            effect:'slideInLeft',
            pauseOnHover:true,
            pauseTime:5000,
            captionOpacity:1,
        });
   });
    $(window).load(function(){
        $('#other-stories').masonry({
            singleMode: true,
            columnWidth: 247,
            itemSelector: '.latest-section'
        });
    });
{% endblock footercode %}

apps/templates/blog/entry_detail.html
{% extends 'blog/base.html' %}
{% load typogrify %}
{% load humanize %}
{% load custom_html %}
{% load more %}
{% load image_tags %}
{% load tagging_tags %}
{% load shorturl %}

{% block facebook %}
<meta property="og:title" content="{{ entry.title }}" />
<meta property="og:type" content="website" />
<meta property="og:url" content="{% shorturl entry %}" />
{% if entry.first_photo %}
<meta property="og:image" content="{{ entry.first_photo.thumbnail_image.url }}" />
{% else %}
<meta property="og:image" content="{{ entry.blog.image.front_image.url }}" />
{% endif %}
<meta property="og:site_name" content="The Queen&#039;s Journal" />
<meta property="fb:admins" content="1653600047" />
{% endblock facebook %}

{% block headcode %}
<link rel="alternate" type="application/rss+xml" title="Latest posts from {{ blog.title }} (RSS 2.0)" href="/rss/blogs/{{ blog.slug }}/" />
{% endblock headcode %}
{% block js %}
    <script type="text/javascript" src="{{ STATIC_URL }}js/plusone.js"></script>
{% endblock %}

{% block title %}{{ entry.title }} - {{ block.super }}{% endblock title %}

    {% block actions %}
        <li><span id="actions-rss" class="action"><a href="/rss/blogs/{{ blog.slug }}/"><span><img src="{{ STATIC_URL }}img/feed.png" />Latest posts RSS</span></a></li>
    {% endblock actions %}
    {% block content %}
        {% block breadcrumb %}
            <div id="breadcrumb" class="nomrg"><a href="{% url front %}" class="homelink">Home</a><span class="divider"></span><a href="{% url blog.views.all_blogs %}">Blogs</a><span class="divider"></span><a href="{% url blog-index blog.slug %}">{{ blog.title }}</a></div>
        {% endblock breadcrumb %}
        <div class="blog-header">
            <div class="blog-header-grad">
                <h1><a href="{% url blog-index blog.slug %}">{{ blog.title }}</a></h1>
            </div>
            <div class="blog-image"><img src="{{ blog.image.header_image.url }}" /></div>
        </div>
        <hr>
    {% block blog-content %}
    <div id="blog-single-entry" class="blog-content">
        <div class="blog-container">
            <h1><a href="{{ entry.get_absolute_url }}">{{ entry.title }}</a></h1>
            <h5>Posted by <a href="{{ entry.author.get_absolute_url }}">{{ entry.author.name }}</a> on {{ entry.pub_date|date:"F j, Y @ h:i a T" }}</h5>
            <br/>
            <div class="blog-post-content">
                <div id="story-socmedia" class="entry">
                    <p class="label">Share<p>
                        <hr>
                    <script src="http://connect.facebook.net/en_US/all.js#xfbml=1"></script><fb:like href="{% shorturl entry %}" layout="button_count" show_faces="false" width="100" font=""></fb:like>
                    <br/>
                    <a href="http://twitter.com/share" class="twitter-share-button" data-url="{% shorturl entry %}" data-count="horizontal" data-via="queensjournal">Tweet</a><script type="text/javascript" src="http://platform.twitter.com/widgets.js"></script>
                    <br/>
                    <a href="http://www.reddit.com/submit" onclick="window.location = 'http://www.reddit.com/submit?url=' + encodeURIComponent(window.location); return false"> <img src="http://www.reddit.com/static/spreddit7.gif" alt="submit to reddit" border="0" /> </a>
                    <br/>
                    <g:plusone></g:plusone>
                    <hr>
                    {% tags_for_object entry as tags %}
                    {% if tags %}
                    <h4>Post tags:</h4>
                    <ul>
                    {% for tag in tags %}
                        <li><a href="/tag/{{tag.name|urlencode}}/">{{ tag }}</a></li>
                    {% endfor %}
                    </ul>
                    {% endif %}
                    <br/>
                    Short URL:
                    <form action="" method="get">
                        <input type="text" id="shorturl" name="shorturl" value="{% shorturl entry %}" />
                    </form>
                    {% revcanonical entry %}

                </div>

                {{ entry.content|more_interior|images:'detail'|removetags:"font"|typogrify|linebreakswithcode|safe }}</div>
        </div>

        <div class="blog-container">
            <h3>Post a comment</h3>
            {% if entry.enable_comments %}
            {% load disqus_tags %}
            <div id="comments" class="blog-container">
                <script type="text/javascript" charset="utf-8">
                        var disqus_developer = 1;
                </script>
                {% disqus_show_comments %}
            </div>
            {% else %}
                <h5>This story is closed to new comments.</h5>
            {% endif %}
        </div>
    </div>
    {% endblock blog-content %}
    {% endblock content %}

apps/templates/blog/entry_list.html
{% extends 'blog/base.html' %}
{% load typogrify %}
{% load custom_html %}
{% load disqus_tags %}
{% load more %}
{% load image_tags %}
{% load tagging_tags %}

{% block headcode %}
<link rel="alternate" type="application/rss+xml" title="Latest posts from {{ blog.title }} (RSS 2.0)" href="/rss/blogs/{{ blog.slug }}/" />
{% endblock headcode %}

{% block title %}{{ block.super }}{% endblock title %}

    {% block actions %}
        <li><a href="/rss/blogs/{{ blog.slug }}/"><span><img src="{{ STATIC_URL }}img/feed.png" /> Latest posts RSS</span></a></li>
    {% endblock actions %}
    {% block blog-filter %}
        {% spaceless %}
        {% if month or author or category or query %}<h3>
        {% if month %}All posts published in {{ month|date:"F Y" }}
        {% else %}{% if author %}All posts written by {{ author.user.first_name }}
        {% else %}{% if category %}All posts in {{ category.name }}
        {% else %}{% if query %}{{ hits }} result{{ hits|pluralize }} for &ldquo;{{ query }}&rdquo; (showing results {{ first_on_page}}&ndash;{{ last_on_page }})
        {% endif %}
        {% endif %}
        {% endif %}
        {% endif %}
        </h3>{% endif %}
        {% endspaceless %}
    {% endblock blog-filter %}

    {% block breadcrumb %}
        <div id="breadcrumb" class="nomrg"><a href="{% url front %}" class="homelink">Home</a><span class="divider"></span><a href="{% url blog.views.all_blogs %}">Blogs</a><span class="divider"></span></div>
    {% endblock breadcrumb %}

    {% block header %}
        <div class="blog-header">
            <div class="blog-header-grad">
                <h1>{{ blog.title }}</h1>
            </div>
            <div class="blog-image"><img src="{{ blog.image.header_image.url }}" /></div>
        </div>
        <hr>
    {% endblock %}

    {% block blog-content %}
        {% for entry in object_list %}
        <div id="entry-{{ entry.id }}" class="entry">
            <h2><a href="{{ entry.get_absolute_url }}">{{ entry.title }}</a></h2>
            <h5>Posted by <a href="{{ entry.author.get_absolute_url }}">{{ entry.author.name }}</a> on {{ entry.pub_date|date:"F j, Y @ h:i a T" }}{% tags_for_object entry as tags %}{% if tags %}<br/>Tags: {% for tag in tags %}<a href="/tag/{{tag.name|urlencode}}/">{{ tag }}</a>{% if not forloop.last %}, {% endif %}{% endfor %}{% endif %}</h5>
            <div class="blog-post-content">{{ entry.content|more:entry.id|images:'list'|removetags:"font"|typogrify|linebreakswithcode|truncatewords:150|safe }}{% ifnotequal entry.content|truncatewords:150|length entry.content|truncatewords:151|length %}<a href="{{ entry.get_absolute_url }}"> Read more...</a>{% endifnotequal %}</div>
            <a href="{{ entry.get_absolute_url }}#disqus_thread" data-disqus-identifier="{{ entry.id }}">View Comments</a>
            {% disqus_num_replies %}
        </div>
        {% endfor %}

    {% if has_next %}<div id="blog-prev" class="side-action">
        {% if author %}<a href="{% url blog_archive_author_pages blog.slug,author.id,next %}">
        {% else %}{% if month %}<a href="{% url blog_archive_month_pages blog.slug,month.year,month|date:"m",next %}">
        {% else %}<a href="{% url blog-index blog.slug,next %}">
        {% endif %}
        {% endif %}
        &laquo; Older posts</a></div>
    {% else %}{% comment %}{% if not has_next and prev_month %}<div id="blog-prev" class="side-action"><a href="{% url blog_archive_month prev_month.year,prev_month|date:"m" %}">&laquo; To {{ prev_month|date:"F Y" }}</a></div>{% endif %}
    {% endcomment %}{% endif %}
    {% if has_previous %}<div id="blog-next" class="side-action">
        {% if author %}<a href="{% url blog_archive_author_pages blog.slug,author.id,previous %}">
        {% else %}{% if month %}<a href="{% url blog_archive_month_pages blog.slug,month.year,month|date:"m",previous %}">
        {% else %}<a href="{% url blog-index blog.slug,previous %}">
        {% endif %}
        {% endif %}
        Newer posts &raquo;</a></div>
    {% else %}{% comment %}{% if not has_previous and next_month %}<div id="blog-next" class="side-action"><a href="{% url blog_archive_month_front next_month.year,next_month|date:"m" %}">To {{ next_month|date:"F Y" }} &raquo;</a></div>{% endif %}
    {% endcomment %}{% endif %}

    {% endblock blog-content %}